name: build-davinci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3
      with:
        repository: ggabrix/android_kernel_samsung_beyondlte
        ref: oneui5_davinci
        path: exynos9820
        fetch-depth: 100

    - name: Checkout gcc toolchain
      uses: actions/checkout@v3
      with:
        repository: mvaisakh/gcc-arm64
        ref: 05cb20a52f12389c3f2340b5103485108feae302
        path: toolchain

    - name: Fetch KernelSU
      run: |
        cd exynos9820
        git submodule update --init --recursive

    - name: Android kernel build
      run: |
        sudo apt install libdebuginfod-dev
        export PATH="$(pwd)/toolchain/bin:${PATH}"
        cd exynos9820
        ./build.sh beyond1lte

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: release-ksu
        path: |
          exynos9820/out/ak3/*.zip
